theme: jekyll-theme-minimal
title: Marco Barulli
description: Experienced entrepreneur and technologist that launched and supported multiple companies. Led by a strong passion for science and its impact on society and the economy. Dedicated worker, with strong organizational and managerial skills. Main areas of expertise: intellectual property, blockchain, startups, sustainable mobility, cryptography.
logo: Marco Barulli - bw 500x500 - no background.png
layouts_dir: /layouts
