theme: jekyll-theme-minimal
title: Marco Barulli
description: Experienced entrepreneur and technologist that launched and supported multiple companies.
logo: Marco Barulli - bw 500x500 - no background.png
layouts_dir: /layouts
